function d(a){this.b=new f(a)}function f(a){this.b=a}
function g(a,b){a instanceof d&&(a=k(a));if(!(a instanceof Function))return a;void 0===a.arity&&(a.arity=a.length);if(b.length===a.arity)switch(a.arity){case 0:return a();case 1:return a(b[0]);default:return a.apply(null,b)}else if(b.length>a.arity)switch(a.arity){case 0:return a();case 1:return g(a(b.shift()),b);default:return g(a.apply(null,b.splice(0,a.arity)),b)}else{var c=function(){return g(a,b.concat(Array.prototype.slice.call(arguments)))};c.arity=a.arity-b.length;return c}}
function k(a){return a instanceof d?a.b instanceof f?a.b=a.b.b():a.b:a}if(!window)var window={};window.Haste={};window.A=g;window.E=k;function l(a){throw a;}var p=new ArrayBuffer(8);new Uint32Array(p);new Float32Array(p);new Float64Array(p);function q(a){l(r(a))}function s(a){return t(a,[0])}function t(a,b,c){var e=c?c:0;return e>=a.length?k(b):[1,[0,a.charCodeAt(e)],new d(function(){return t(a,b,e+1)})]}
function r(a){var b="";for(a=k(a);1==a[0];a=k(a[2]))b+=String.fromCharCode(k(a[1])[1]);return b}var u=isNaN;if("undefined"==typeof aa)var aa=void 0;function ba(a){window.setTimeout(function(){g(a,[0])},10)}function ca(a,b){return a[b].toString()}function w(a){return(a=document.getElementById(a))?[1,[0,a]]:[0]}function x(a,b,c){b=new ArrayBuffer(b);(new window[a](b))[0]=c;return b}
function y(a,b,c){var e=new ArrayBuffer(b);(new window[a](e))[0]=c;a=new Uint8Array(e);c=0;for(b-=1;c<b;++c,--b){var h=a[c];a[c]=a[b];a[b]=h}return e}window.toABle=x;window.toABbe=y;var z=new ArrayBuffer(2);(new DataView(z)).setInt16(0,256,!0);256!==(new Int16Array(z))[0]&&(window.toABle=y,window.toABbe=x);function B(a,b){this.a=[];this.c=b;for(var c=!0,e=a.length-1;0<=e;e--){var h=a[e]|0;c&&h==b||(this.a[e]=h,c=!1)}}var C={};
function G(a){if(!(-128<=a&&128>a&&C[a])){var b=new B([a|0],0>a?-1:0);-128<=a&&128>a&&(C[a]=b)}}function H(a){return new B(a,a[a.length-1]&-2147483648?-1:0)}G(0);G(1);G(16777216);function I(a,b){if(a.c!=b.c)return!1;for(var c=Math.max(a.a.length,b.a.length),e=0;e<c;e++)if((0>e?0:e<a.a.length?a.a[e]:a.c)!=(0>e?0:e<b.a.length?b.a[e]:b.c))return!1;return!0}function da(){}var J={};function K(a){if(!(-128<=a&&128>a&&J[a])){var b=new da;-128<=a&&128>a&&(J[a]=b)}}K(0);K(1);K(-1);K(16777216);
H([4294967295,4294967295]);H([0,0,1]);var L=[0],M=[0,0],ea=[0,M,M],fa=[0,M,M],ga=[0,M,M];function N(a,b){var c=ca(a,r(k(b)));return new d(function(){return s(k(c))})}function O(a,b,c,e){return g(a,[new d(function(){return function(){var a=k(b)[1],m=r(k(c)),n=r(k(e));a[m]=n;return 0}})])}var ha=s("base"),ia=s("GHC.IO.Exception"),ja=s("IOException"),ka=[0,H([4053623282,1685460941]),H([3693590983,2507416641]),ha,ia,ja],la=[0,H([4053623282,1685460941]),H([3693590983,2507416641]),ka,L];
function P(){return k(la)}var ma=s("Maybe.fromJust: Nothing"),na=new d(function(){return q(ma)});function oa(a,b){var c=new d(function(){var e=g(a,[b]),h=g(P,[new d(function(){var a=k(c);return 0==a[0]?k(na):k(a[1])})]),m=I(e[1],h[1]);return k(m)?(e=I(e[2],h[2]),0==k(e)?[0]:[1,b]):[0]});return k(c)}function pa(a){a=k(a);return oa(k(k(a[1])[1]),a[2])}var Q=s(": "),qa=[0,41],ra=s(" (");function R(a,b){var c=k(a);return 0==c[0]?k(b):[1,c[1],new d(function(){return R(c[2],b)})]}
var sa=s("already exists"),ta=s("does not exist"),ua=s("protocol error"),va=s("failed"),wa=s("invalid argument"),xa=s("inappropriate type"),ya=s("hardware fault"),za=s("unsupported operation"),Aa=s("timeout"),Ba=s("resource vanished"),Ca=s("interrupted"),Da=s("resource busy"),Ea=s("resource exhausted"),Fa=s("end of file"),Ga=s("illegal operation"),Ha=s("permission denied"),Ia=s("user error"),Ja=s("unsatisified constraints"),Ka=s("system error");
function La(a,b){switch(k(a)){case 0:return R(sa,b);case 1:return R(ta,b);case 2:return R(Da,b);case 3:return R(Ea,b);case 4:return R(Fa,b);case 5:return R(Ga,b);case 6:return R(Ha,b);case 7:return R(Ia,b);case 8:return R(Ja,b);case 9:return R(Ka,b);case 10:return R(ua,b);case 11:return R(va,b);case 12:return R(wa,b);case 13:return R(xa,b);case 14:return R(ya,b);case 15:return R(za,b);case 16:return R(Aa,b);case 17:return R(Ba,b);default:return R(Ca,b)}}var Ma=[0,125],Na=s("{handle: ");
function S(a,b,c,e,h,m){var n=new d(function(){var a=new d(function(){return La(b,new d(function(){var a=k(e);return 0==a[0]?k(m):R(ra,new d(function(){return R(a,[1,qa,m])}))}))}),h=k(c);return 0==h[0]?k(a):R(h,new d(function(){return R(Q,a)}))});h=k(h);if(h[0])return R(h[1],new d(function(){return R(Q,n)}));a=k(a);if(a[0]){var v=k(a[1]);return R(Na,new d(function(){return R(v[1],[1,Ma,new d(function(){return R(Q,n)})])}))}return k(n)}
function T(a,b){var c=k(a);return S(c[1],c[2],c[3],c[4],c[6],b)}var Oa=[0,44],Pa=[0,93],Qa=[0,91];function Ra(a,b){var c=k(a);return 0==c[0]?t("[]",b):[1,Qa,new d(function(){return g(T,[c[1],new d(function(){function a(c){var m=k(c);return 0==m[0]?k([1,Pa,b]):[1,Oa,new d(function(){return g(T,[m[1],new d(function(){return a(m[2])})])})]}return a(c[2])})])})]}
var Sa=[0,function(a,b,c){a=k(b);return S(a[1],a[2],a[3],a[4],a[6],c)},function(a){a=k(a);return S(a[1],a[2],a[3],a[4],a[6],L)},function(a,b){return Ra(a,b)}],Ta=new d(function(){return[0,P,Sa,U,pa]});function U(a){return[0,Ta,a]}var V=[0];function W(a){return l(new d(function(){return U(new d(function(){return[0,V,7,L,a,V,V]}))}))}function Y(a){return k(a)}
var Z=s("height"),Ua=s("width"),Va=s("clientHeight"),Wa=s("clientWidth"),Xa=s("Pattern match failure in do expression at DolanP.hs:25:3-13"),Ya=s("Pattern match failure in do expression at DolanP.hs:26:3-14"),Za=s("Pattern match failure in do expression at DolanP.hs:28:3-12"),$a=s("Pattern match failure in do expression at DolanP.hs:29:3-13"),ab=s("MAIN_HTML"),bb=s("canvas"),cb=s(" could be found!");function db(a){return q(t("No element with ID ",new d(function(){return R(a,cb)})))}
function eb(a){var b=k(ab),c=w(r(b)),c=k(c);if(c[0]){var c=N(k(c[1])[1],Wa),e=Number(r(k(c))),c=u(e);if(k(c))return W(Xa);c=w(r(b));c=k(c);if(c[0]){var b=N(k(c[1])[1],Va),h=Number(r(k(b))),b=u(h);if(k(b))return W(Ya);b=k(bb);c=w(r(b));c=k(c);if(c[0]&&(g(O,[Y,c[1],Ua,new d(function(){var a=.9*e,b=a&4294967295;return a>=b?s(k(String(b))):s(k(String(b-1|0)))}),a]),c=w(r(b)),c=k(c),c[0]&&(g(O,[Y,c[1],Z,new d(function(){var a=.9*h,b=a&4294967295;return a>=b?s(k(String(b))):s(k(String(b-1|0)))}),a]),a=
w(r(b)),a=k(a),a[0]))){a=N(k(a[1])[1],Ua);a=Number(r(k(a)));c=u(a);if(k(c))return W(Za);c=w(r(b));c=k(c);if(c[0])return b=N(k(c[1])[1],Z),b=Number(r(k(b))),c=u(b),0==k(c)?[0,[0,a],[0,b]]:W($a)}}}return db(b)}function fb(){return 0}function $(a){var b=k(a);if(b[0]){var c=k(b[1]);return function(a){a=k(a)[1];var h=k(c[1])[1],m=k(c[2])[1];a.moveTo(h,m);a:{for(h=b[2];;)if(h=k(h),h[0]){var n=k(h[1]),m=k(n[1])[1],n=k(n[2])[1];a.lineTo(m,n);h=h[2]}else{a=0;break a}a=void 0}return a}}return k(fb)}
var gb=[0,10];
function hb(a,b,c,e,h,m){b.width=b.width;var n=k(a);a=n[1];a.save();a.translate(.3*c,.3*e);a.save();a.scale(1,-1);a.beginPath();g($,[[1,fa,[1,[0,M,[0,.2*e]],L]],n,m]);g($,[[1,[0,M,[0,.1*e]],[1,[0,[0,.6*c],[0,.1*e]],L]],n,m]);a.stroke();a.restore();a.restore();a.save();a.translate(.2*c-.1*e,.5*e);a.save();a.scale(1,-1);a.beginPath();g($,[[1,ea,[1,[0,[0,.2*e],M],L]],n,m]);g($,[[1,[0,[0,.1*e],M],[1,[0,[0,.1*e],[0,-(.4*e)]],L]],n,m]);a.stroke();a.restore();a.restore();a.save();a.translate(.2*c,.2*e);
a.beginPath();var v=.1*e;a.moveTo(v,0);a.arc(0,0,v,0,6.283185307179586);a.stroke();a.beginPath();var X=new d(function(){return[0,k(h)[1]/1E3]}),F=new d(function(){return[0,v*Math.cos(k(X)[1])]}),D=new d(function(){return[0,v*Math.sin(k(X)[1])]});g($,[[1,ga,[1,[0,F,D],L]],n,m]);a.stroke();a.beginPath();g($,[[1,[0,F,D],[1,[0,[0,.1*c],D],L]],n,m]);a.stroke();a.beginPath();g($,[[1,[0,F,D],[1,[0,F,[0,.3*e]],L]],n,m]);a.stroke();a.restore();ba(function(a){var c=eb(a),c=k(c);return hb(n,b,k(c[1])[1],k(c[2])[1],
new d(function(){return[0,k(h)[1]+k(gb)[1]]}),a)});return 0}function ib(a,b){return g(a,[function(){var a=w(r(k(b))),a=k(a);0==a[0]?a=V:(a=k(a[1])[1],a=k(!!a.getContext)?[1,[0,[0,a.getContext("2d")],[0,a]]]:V);return a}])}var jb=s("Pattern match failure in do expression at DolanP.hs:70:3-13");function kb(a){var b=g(ib,[Y,bb,a]),b=k(b);if(b[0]){var c=eb(a),c=k(c),b=k(b[1]);a=hb(b[1],k(b[2])[1],k(c[1])[1],k(c[2])[1],M,a)}else a=W(jb);return a}window.onload=function(){g(kb,[0])};
