// Generated by CoffeeScript 1.4.0
(function() {
  var Block, Bot, GAConfig, GeneticAlgorithm, NN, NNConfig, Neuron, ReqAnimFrameShim, SubSystem, SubSystemAmmoJs, SubSystemThreeJs, initPhysics, randomB, randomlySelectFromArray, updatePhysics,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Block = (function() {

    function Block(pos, world, scene) {
      this.blockGeom = new THREE.CubeGeometry(0.3, 0.3, 0.3);
      this.blockMat = new THREE.MeshBasicMaterial({
        wireframe: true
      });
      this.block = new Physijs.BoxMesh(this.blockGeom, this.blockMat, 0.0, {
        restitution: .2
      });
      this.block.position.copy(pos);
      this.block.myTag = this;
      scene.add(this.block);
    }

    return Block;

  })();

  window.Block = Block;

  Bot = (function() {

    function Bot(world, scene) {
      this.lTrackInput = 0;
      this.rTrackInput = 0;
      this.bodyGeom = new THREE.CubeGeometry(1, 1, 1);
      this.bodyMat = new THREE.MeshBasicMaterial({
        wireframe: true
      });
      this.body = new Physijs.BoxMesh(this.bodyGeom, this.bodyMat, 1.0, {
        restitution: .2
      });
      this.body.matrixAutoUpdate = false;
      this.wheelRadius = 0.2;
      this.wheelWidth = 0.3;
      this.wheelLeftGeom = new THREE.CylinderGeometry(this.wheelRadius, this.wheelRadius, this.wheelWidth, 32, 32, false);
      this.wheelLeftMat = new THREE.MeshBasicMaterial({
        wireframe: true
      });
      this.wheelLeft = new THREE.Mesh(this.wheelLeftGeom, this.wheelLeftMat);
      this.wheelLeft.rotation.z = -Math.PI / 2;
      this.wheelLeft.position.x = 1.0;
      this.wheelLeft.position.y = -0.5;
      this.wheelRightGeom = new THREE.CylinderGeometry(this.wheelRadius, this.wheelRadius, this.wheelWidth, 32, 32, false);
      this.wheelRightMat = new THREE.MeshBasicMaterial({
        wireframe: true
      });
      this.wheelRight = new THREE.Mesh(this.wheelRightGeom, this.wheelRightMat);
      this.wheelRight.rotation.z = -Math.PI / 2;
      this.wheelRight.position.x = -1.0;
      this.wheelRight.position.y = -0.5;
      this.body.add(this.wheelLeft);
      this.body.add(this.wheelRight);
      scene.add(this.body);
      /*
              @body.addEventListener( 'collision', (( other_object, linear_velocity, angular_velocity ) -> 
                  #console.log other_object
                  scene.remove( other_object )
              ))
      */

    }

    Bot.prototype.update = function() {
      var d, rot, v, v1;
      rot = (-this.lTrackInput + this.rTrackInput) * 0.05;
      d = (this.lTrackInput + this.rTrackInput) * 0.05;
      v = this.body.localToWorld(new THREE.Vector3(0, 0, 1.0));
      v1 = v.sub(this.body.position);
      v1.y = 0;
      v1.normalize();
      v1.multiplyScalar(d);
      this.body.position.add(v1);
      this.body.rotation.add(new THREE.Vector3(0, rot, 0));
      this.body.__dirtyPosition = true;
      this.body.__dirtyRotation = true;
      return this.body.updateMatrix();
    };

    Bot.prototype.setInput = function(l, r) {
      this.lTrackInput = l;
      return this.rTrackInput = r;
    };

    return Bot;

  })();

  window.Bot = Bot;

  randomB = function(min, max) {
    return (Math.random() * (max - min)) + min;
  };

  randomlySelectFromArray = function(array) {
    return array[Math.floor(Math.random() * array.length)];
  };

  GAConfig = (function() {

    function GAConfig() {
      this.hallOfFameSize = 0;
      this.populationSize = 0;
      this.chromosomeLength = 0;
      this.boundaries = null;
      this.maxIterations = 100;
      this.pStart = 0.2;
      this.pEnd = 0.9;
      this.kStart = 0.1;
      this.kEnd = 0.9;
      this.mutationRangeStart = 10.0;
      this.mutationRangeEnd = 0.1;
      this.mutationRateStart = 0.9;
      this.mutationRateEnd = 0.01;
      this.numParentsForCrossover = 2;
    }

    return GAConfig;

  })();

  GeneticAlgorithm = (function() {

    function GeneticAlgorithm(gaConfig) {
      this.gaConfig = gaConfig;
    }

    GeneticAlgorithm.prototype.nothing = function() {};

    GeneticAlgorithm.prototype.createChromosome = function() {
      var chromosome, max, min, _i, _len, _ref, _ref1;
      chromosome = new Array();
      if ((this.gaConfig.boundaries != null)) {
        _ref = this.gaConfig.boundaries;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          _ref1 = _ref[_i], min = _ref1[0], max = _ref1[1];
          chromosome.push(randomB(min, max));
        }
      } else {
        console.log("GA: createChromosome() failed, Boundaries should be defined");
      }
      return chromosome;
    };

    GeneticAlgorithm.prototype.initialize = function() {
      this.currentPopulation = new Array();
      while (this.currentPopulation.push(this.createChromosome()) < this.gaConfig.populationSize) {
        this.nothing();
      }
      return this.currentIteration = 0;
    };

    GeneticAlgorithm.prototype.fromPercentage = function(percentage, start, end) {
      return (percentage * (end - start)) + start;
    };

    GeneticAlgorithm.prototype.update = function(fitnesses) {
      var child, children, mChild, mutatedChildren, oldPopulation, parents, _i, _j, _len, _len1;
      this.percentProgress = this.currentIteration / this.gaConfig.maxIterations;
      this.p = this.fromPercentage(this.percentProgress, this.gaConfig.pStart, this.gaConfig.pEnd);
      this.k = Math.floor(this.fromPercentage(this.percentProgress, this.gaConfig.kStart, this.gaConfig.kEnd) * this.gaConfig.populationSize);
      this.mRate = this.fromPercentage(this.percentProgress, this.gaConfig.mutationRateStart, this.gaConfig.mutationRateEnd);
      this.mRange = this.fromPercentage(this.percentProgress, this.gaConfig.mutationRangeStart, this.gaConfig.mutationRangeEnd);
      oldPopulation = this.currentPopulation;
      this.currentPopulation = new Array();
      while (this.currentPopulation.length < this.gaConfig.populationSize) {
        parents = new Array();
        while (parents.length < this.gaConfig.numParentsForCrossover) {
          parents.push(this.tournamentSelect(oldPopulation, fitnesses));
        }
        children = this.crossover(parents);
        mutatedChildren = [];
        for (_i = 0, _len = children.length; _i < _len; _i++) {
          child = children[_i];
          mutatedChildren.push(this.mutate(child));
        }
        for (_j = 0, _len1 = mutatedChildren.length; _j < _len1; _j++) {
          mChild = mutatedChildren[_j];
          this.currentPopulation.push(mChild);
        }
      }
      if (this.currentIteration < this.gaConfig.maxIterations) {
        this.currentIteration++;
      }
      return this.currentPopulation;
    };

    GeneticAlgorithm.prototype.mutate = function(child) {
      var gene, mutatedChild, p, _i, _len;
      mutatedChild = [];
      for (_i = 0, _len = child.length; _i < _len; _i++) {
        gene = child[_i];
        p = Math.random();
        if (p < this.mRate) {
          mutatedChild.push(gene + randomB(-this.mRange, this.mRange));
        } else {
          mutatedChild.push(gene);
        }
      }
      return mutatedChild;
    };

    GeneticAlgorithm.prototype.crossover = function(parents) {
      var child0, child1, crossoverPoint, mutatedChildren, parent0, parent1, _ref, _ref1;
      crossoverPoint = Math.floor(randomB(0, parents[0].length));
      parent0 = parents[0], parent1 = parents[1];
      child0 = parent0;
      if (crossoverPoint < child0.length) {
        [].splice.apply(child0, [crossoverPoint, (child0.length - 1) - crossoverPoint + 1].concat(_ref = parent1.slice(crossoverPoint, +(child0.length - 1) + 1 || 9e9))), _ref;
      }
      child1 = parent1;
      if (crossoverPoint < child1.length) {
        [].splice.apply(child1, [crossoverPoint, (child1.length - 1) - crossoverPoint + 1].concat(_ref1 = parent0.slice(crossoverPoint, +(child1.length - 1) + 1 || 9e9))), _ref1;
      }
      return mutatedChildren = [child0, child1];
    };

    GeneticAlgorithm.prototype.tournamentSelect = function(oldPopulation, fitnesses) {
      var i, p, r, randomIndex, tourn;
      tourn = [];
      while (tourn.length < this.k) {
        randomIndex = Math.floor(Math.random() * oldPopulation.length);
        tourn.push([oldPopulation[randomIndex], fitnesses[randomIndex]]);
      }
      tourn.sort(function(a, b) {
        return a[1] - b[1];
      });
      r = Math.random();
      p = this.p;
      i = 0;
      while (r > p && (i < tourn.length - 1)) {
        i++;
        p += p * Math.pow(1 - p, i);
      }
      return tourn[i][0];
    };

    return GeneticAlgorithm;

  })();

  window.GAConfig = GAConfig;

  window.GeneticAlgorithm = GeneticAlgorithm;

  NNConfig = (function() {

    function NNConfig(layerSizes, chromosome) {
      var currentLayer, currentLayerSize, i, prevLayerSize, _i, _j, _len, _ref;
      this.layers = [];
      prevLayerSize = layerSizes[0];
      _ref = layerSizes.slice(1);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        currentLayerSize = _ref[_i];
        currentLayer = [];
        for (i = _j = 1; 1 <= currentLayerSize ? _j <= currentLayerSize : _j >= currentLayerSize; i = 1 <= currentLayerSize ? ++_j : --_j) {
          currentLayer.push(new Neuron(chromosome.splice(0, prevLayerSize)));
        }
        this.layers.push(currentLayer);
        prevLayerSize = currentLayerSize;
      }
    }

    return NNConfig;

  })();

  Neuron = (function() {

    function Neuron(weightsWithBias) {
      this.activation = __bind(this.activation, this);
      this.weights = weightsWithBias.slice(0, +(weightsWithBias.length - 2) + 1 || 9e9);
      this.bias = weightsWithBias[weightsWithBias.length - 1];
    }

    Neuron.prototype.evaluate = function(input) {
      var i, sum, weight, _i, _len, _ref;
      i = 0;
      sum = 0;
      _ref = this.weights;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        weight = _ref[_i];
        sum += weight * input[i];
        i++;
      }
      sum += this.bias;
      return this.activation(sum);
    };

    Neuron.prototype.activation = function(sum) {
      return 1.0 / (1.0 + Math.exp(-sum));
    };

    return Neuron;

  })();

  NN = (function() {

    function NN(nnConfig) {
      this.nnConfig = nnConfig;
    }

    NN.prototype.evaluate = function(input) {
      var currentLayerValues, layer, neuron, prevLayerValues, _i, _j, _len, _len1, _ref;
      prevLayerValues = input;
      currentLayerValues = [];
      _ref = this.nnConfig.layers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        layer = _ref[_i];
        for (_j = 0, _len1 = layer.length; _j < _len1; _j++) {
          neuron = layer[_j];
          currentLayerValues.push(neuron.evaluate(prevLayerValues));
        }
        prevLayerValues = currentLayerValues;
        currentLayerValues = [];
      }
      return prevLayerValues;
    };

    NN.prototype.toChromosome = function() {
      var chromosome, layer, neuron, _i, _j, _len, _len1, _ref;
      chromosome = [];
      _ref = this.nnConfig.layers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        layer = _ref[_i];
        for (_j = 0, _len1 = layer.length; _j < _len1; _j++) {
          neuron = layer[_j];
          chromosome = chromosome.concat(neuron.weights);
          chromosome.push(neuron.bias);
        }
      }
      return chromosome;
    };

    return NN;

  })();

  window.NNConfig = NNConfig;

  window.NN = NN;

  initPhysics = function() {
    var boxAmmo, boxShape, groundAmmo, groundMass, groundShape, groundTransform, localInertia, mass, motionState, rbInfo, startTransform;
    this.collisionConfiguration = new Ammo.btDefaultCollisionConfiguration();
    this.dispatcher = new Ammo.btCollisionDispatcher(this.collisionConfiguration);
    this.overlappingPairCache = new Ammo.btDbvtBroadphase();
    this.solver = new Ammo.btSequentialImpulseConstraintSolver();
    this.world = new Ammo.btDiscreteDynamicsWorld(this.dispatcher, this.overlappingPairCache, this.solver, this.collisionConfiguration);
    this.world.setGravity(new Ammo.btVector3(0, -6.0, 0));
    groundTransform = new Ammo.btTransform();
    groundTransform.setIdentity();
    groundTransform.setOrigin(new Ammo.btVector3(0, -6, 0));
    groundMass = 0;
    motionState = new Ammo.btDefaultMotionState(groundTransform);
    groundShape = new Ammo.btBoxShape(new Ammo.btVector3(5, 1, 5));
    localInertia = new Ammo.btVector3(0, 0, 0);
    rbInfo = new Ammo.btRigidBodyConstructionInfo(groundMass, motionState, groundShape, localInertia);
    groundAmmo = new Ammo.btRigidBody(rbInfo);
    this.world.addRigidBody(groundAmmo);
    this.boxes = [];
    mass = 3 * 3 * 3;
    startTransform = new Ammo.btTransform();
    startTransform.setIdentity();
    startTransform.setOrigin(new Ammo.btVector3(0.0, 10, 0.0));
    localInertia = new Ammo.btVector3(0, 0, 0);
    boxShape = new Ammo.btBoxShape(new Ammo.btVector3(0.5, 0.5, 0.5));
    boxShape.calculateLocalInertia(mass, localInertia);
    motionState = new Ammo.btDefaultMotionState(startTransform);
    rbInfo = new Ammo.btRigidBodyConstructionInfo(mass, motionState, boxShape, localInertia);
    boxAmmo = new Ammo.btRigidBody(rbInfo);
    this.world.addRigidBody(boxAmmo);
    return this.boxes.push(boxAmmo);
  };

  updatePhysics = function(ms) {
    var box, origin, rotation;
    this.world.stepSimulation(ms, 5);
    this.transform = new Ammo.btTransform();
    box = this.boxes[0];
    box.getMotionState().getWorldTransform(transform);
    origin = transform.getOrigin();
    this.cube.position.x = origin.x();
    this.cube.position.y = origin.y();
    this.cube.position.z = origin.z();
    rotation = transform.getRotation();
    this.cube.quaternion.x = rotation.x();
    this.cube.quaternion.y = rotation.y();
    this.cube.quaternion.z = rotation.z();
    return this.cube.quaternion.w = rotation.w();
  };

  ReqAnimFrameShim = (function() {

    function ReqAnimFrameShim() {
      this.requestAnimFrameShim();
    }

    /* RequestAnimationFrame shim. yoinked from https://github.com/soulwire/Coffee-Physics/blob/master/source/base.coffee
    */


    ReqAnimFrameShim.prototype.requestAnimFrameShim = function() {
      var time, vendor, vendors, _i, _len;
      time = 0;
      vendors = ['ms', 'moz', 'webkit', 'o'];
      for (_i = 0, _len = vendors.length; _i < _len; _i++) {
        vendor = vendors[_i];
        if (!(!window.requestAnimationFrame)) {
          continue;
        }
        window.requestAnimationFrame = window[vendor + 'RequestAnimationFrame'];
        window.cancelRequestAnimationFrame = window[vendor + 'CancelRequestAnimationFrame'];
      }
      if (!window.requestAnimationFrame) {
        window.requestAnimationFrame = function(callback, element) {
          var delta, now, old;
          now = new Date().getTime();
          delta = Math.max(0, 16 - (now - old));
          setTimeout((function() {
            return callback(time + delta);
          }), delta);
          return old = now + delta;
        };
      }
      if (!window.cancelAnimationFrame) {
        return window.cancelAnimationFrame = function(id) {
          return clearTimeout(id);
        };
      }
    };

    return ReqAnimFrameShim;

  })();

  window.ReqAnimFrameShim = ReqAnimFrameShim;

  SubSystem = (function() {

    function SubSystem() {}

    SubSystem.prototype.init = function() {};

    SubSystem.prototype.update = function(ms) {};

    return SubSystem;

  })();

  SubSystemThreeJs = (function(_super) {

    __extends(SubSystemThreeJs, _super);

    function SubSystemThreeJs() {
      return SubSystemThreeJs.__super__.constructor.apply(this, arguments);
    }

    SubSystemThreeJs.prototype.init = function() {};

    SubSystemThreeJs.prototype.update = function(ms) {};

    return SubSystemThreeJs;

  })(SubSystem);

  SubSystemAmmoJs = (function() {

    function SubSystemAmmoJs() {}

    SubSystemAmmoJs.prototype.init = function() {};

    SubSystemAmmoJs.prototype.update = function(ms) {};

    return SubSystemAmmoJs;

  })();

  (function() {
    var evalFitness, extractSimulatees, getAverageFitness, getBestFitness, getBotForwardVector, getClosestBlockVector, getMaxBestAndAvg, init, initBlocks, initGA, initInputStreams, initScene, rafs, renderBotPerceptions, showInfo, update, updateCamera, updateGA, updatePicking, updateUpdateBus;
    rafs = new ReqAnimFrameShim();
    Physijs.scripts.worker = 'Physijs/physijs_worker.js';
    Physijs.scripts.ammo = '../ammo.js/builds/ammo.fast.js';
    this.width = 640;
    this.height = 480;
    this.azimuth = 0.0;
    this.altitude = Math.PI / 4;
    this.kLeft = 37;
    this.kUp = 38;
    this.kRight = 39;
    this.kDown = 40;
    this.mouse = {
      x: void 0,
      y: void 0
    };
    this.keys = [];
    this.keys[this.kLeft] = false;
    this.keys[this.kUp] = false;
    this.keys[this.kRight] = false;
    this.keys[this.kDown] = false;
    $(document).ready(function() {
      return init();
    });
    showInfo = function(object) {
      var property, str;
      if ((!(this.currentSelected != null)) || (this.currentSelected !== object)) {
        this.currentSelected = object;
      }
      $("#forInfo").empty();
      str = "<div id=\"toAccordion\">";
      for (property in object) {
        str += "<div class=\"group\"><h3>" + property + "</h3><div>" + property + "</div></div>";
      }
      str += "</div>";
      $("#generatedInfoDiv").append(str);
      $("#forInfo").append(str);
      return $("#toAccordion").accordion({
        header: "> div > h3"
      }).sortable({
        axis: "y",
        handle: "h3",
        stop: function(event, ui) {
          return ui.item.children("h3").triggerHandler("focusout");
        }
      });
    };
    initScene = function() {
      var func, parametricFunc, uTransform, vTransform, xMax, xMin, zMax, zMin;
      this.scene = new Physijs.Scene;
      this.scene.setGravity(new THREE.Vector3(0, 0, 0));
      this.camera = new THREE.PerspectiveCamera(60, this.width / this.height, 0.1, 1000);
      this.renderer = new THREE.WebGLRenderer();
      this.renderer.setSize(this.width, this.height);
      this.renderer.setClearColor({
        r: 0.0,
        g: 0.0,
        b: 0.0
      }, 1.0);
      this.currentSelected = null;
      this.currentSelectedDomElement = null;
      this.clickStream = $(this.renderer.domElement).asEventStream("mousedown").filter(function(_) {
        return this.INTERSECTED != null;
      });
      this.clickStream.onValue(function(e) {
        var vec;
        if (this.INTERSECTED === this.cube) {
          if ((this.vector != null)) {
            vec = this.vector.clone();
            vec.normalize();
            vec.multiplyScalar(20);
            vec.y *= -10;
            return console.log(vec);
          }
        }
      });
      this.renderer.shadowMapEnabled = true;
      this.renderDivElement = document.createElement("div");
      this.renderDivElement.appendChild(this.renderer.domElement);
      $("#forCanvas").append(this.renderer.domElement);
      this.canvasMouseMoveStream = $(this.renderer.domElement).asEventStream("mousemove");
      this.canvasMouseMoveStream.onValue(function(e) {
        this.mouse.x = (e.offsetX / this.width) * 2 - 1;
        return this.mouse.y = ((e.offsetY / this.height) * 2 - 1) * -1;
      });
      this.geometry = new THREE.CubeGeometry(1, 1, 1);
      this.material = new THREE.MeshPhongMaterial({
        ambient: 0x444444,
        color: 0x8844AA,
        shininess: 300,
        specular: 0x33AA33,
        shading: THREE.SmoothShading
      });
      this.cube = new THREE.Mesh(this.geometry, this.material);
      xMin = -10.0;
      xMax = 10.0;
      zMin = 10.0;
      zMax = -10.0;
      func = function(x, z) {
        return x * x + z * z;
      };
      uTransform = function(u) {
        return (u * (xMax - xMin)) + xMin;
      };
      vTransform = function(v) {
        return (v * (zMax - zMin)) + zMin;
      };
      parametricFunc = function(u, v) {
        var x, y, z;
        x = uTransform(u);
        z = vTransform(v);
        y = func(x, z);
        return new THREE.Vector3(x, y, z);
      };
      this.planeGeom = new THREE.PlaneGeometry(1000, 1000, 100, 100);
      this.planeMat = new THREE.MeshPhongMaterial({
        ambient: 0x444444,
        color: 0x554455,
        shininess: 10,
        specular: 0x33AA33,
        shading: THREE.SmoothShading
      });
      /*@planeMat = new THREE.MeshBasicMaterial({
          wireframe:true
      })
      */

      this.plane = new THREE.Mesh(this.planeGeom, this.planeMat);
      this.plane.position.y = 0;
      this.plane.rotation.x = -Math.PI / 2;
      this.plane.receiveShadow = true;
      this.axisHelper = new THREE.AxisHelper(10);
      this.scene.add(this.axisHelper);
      this.myBot = new Bot(this.world, this.scene);
      this.myBot.body.position.y = 0.7;
      this.myBot.body.position.z = 5.0;
      this.camera.position.x = 0;
      this.camera.position.y = 15;
      this.camera.position.z = 0;
      this.camera.lookAt(this.scene.position);
      this.ambient = new THREE.AmbientLight(0x777777);
      this.scene.add(this.ambient);
      this.light = new THREE.SpotLight(0x4444cc);
      this.light.position.set(0, 10, 0);
      this.light.castShadow = true;
      this.light.target.position.set(0, 0, 0);
      this.light.shadowCameraNear = 0.01;
      this.light.shadowCameraFar = 4000;
      this.light.shadowCameraFov = 60;
      this.scene.add(this.light);
      return this.projector = new THREE.Projector();
    };
    initBlocks = function() {
      var block, i, max, min, r1, r3, _i, _ref, _results;
      this.numBlocks = 200;
      this.blocks = [];
      max = 10;
      min = -10;
      _results = [];
      for (i = _i = 1, _ref = this.numBlocks; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
        r1 = (Math.random() * (max - min)) + min;
        r3 = (Math.random() * (max - min)) + min;
        block = new Block(new THREE.Vector3(r1, 0.7, r3), this.world, this.scene);
        _results.push(this.blocks.push(block));
      }
      return _results;
    };
    getMaxBestAndAvg = function() {
      var avg, best, maxAvg, maxBest, _i, _len, _ref, _ref1;
      maxBest = 0;
      maxAvg = 0;
      _ref = this.graphData;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _ref1 = _ref[_i], best = _ref1.best, avg = _ref1.avg;
        if (best > maxBest) {
          maxBest = best;
        }
        if (avg > maxAvg) {
          maxAvg = avg;
        }
      }
      return [maxBest, maxAvg];
    };
    initGA = function() {
      this.gaConfig = new GAConfig();
      this.gaConfig.populationSize = 100;
      this.gaConfig.boundaries = [[-1000, 1000], [-1000, 1000]];
      this.ga = new GeneticAlgorithm(this.gaConfig);
      this.ga.initialize();
      return this.simulatees = this.ga.currentPopulation;
    };
    initInputStreams = function() {
      var botLeftTrackBackwardsKeyDown, botLeftTrackForwardsKeyDown, botLeftTrackInput, botLeftTrackKeyUp, botRightTrackBackwardsKeyDown, botRightTrackForwardsKeyDown, botRightTrackInput, botRightTrackKeyUp, botTracksInput, keyDown, keyUp;
      keyDown = $(document).asEventStream("keydown");
      keyUp = $(document).asEventStream("keyup");
      keyDown.onValue(function(x) {
        return this.keys[x.keyCode] = true;
      });
      keyUp.onValue(function(x) {
        return this.keys[x.keyCode] = false;
      });
      botLeftTrackForwardsKeyDown = keyDown.filter(function(x) {
        if (x.keyCode === 81) {
          return true;
        }
      }).map(1.0);
      botLeftTrackBackwardsKeyDown = keyDown.filter(function(x) {
        if (x.keyCode === 65) {
          return true;
        }
      }).map(-1.0);
      botLeftTrackKeyUp = keyUp.filter(function(x) {
        return x.keyCode === 81 || x.keyCode === 65;
      }).map(0.0);
      botLeftTrackInput = botLeftTrackForwardsKeyDown.merge(botLeftTrackBackwardsKeyDown).merge(botLeftTrackKeyUp).skipDuplicates().toProperty(0.0);
      botRightTrackForwardsKeyDown = keyDown.filter(function(x) {
        if (x.keyCode === 87) {
          return true;
        }
      }).map(1.0);
      botRightTrackBackwardsKeyDown = keyDown.filter(function(x) {
        if (x.keyCode === 83) {
          return true;
        }
      }).map(-1.0);
      botRightTrackKeyUp = keyUp.filter(function(x) {
        return x.keyCode === 87 || x.keyCode === 83;
      }).map(0.0);
      botRightTrackInput = botRightTrackForwardsKeyDown.merge(botRightTrackBackwardsKeyDown).merge(botRightTrackKeyUp).skipDuplicates().toProperty(0.0);
      /*
              botLeftTrackInput.combine(botRightTrackInput, 
                  (l, r) -> [l, r]
              ).log()
      */

      botTracksInput = botLeftTrackInput.combine(botRightTrackInput, function(l, r) {
        return [l, r];
      });
      return botTracksInput.onValue(function(_arg) {
        var l, r;
        l = _arg[0], r = _arg[1];
        if (this.myBot != null) {
          return this.myBot.setInput(l, r);
        }
      });
    };
    init = function() {
      var chrmsm, nnConfig, num;
      initScene();
      initBlocks();
      this.myBot.body.addEventListener('collision', (function(other_object, linear_velocity, angular_velocity) {
        var block, max, min, r1, r3;
        max = 10;
        min = -10;
        block = other_object.myTag;
        r1 = (Math.random() * (max - min)) + min;
        r3 = (Math.random() * (max - min)) + min;
        block.block.position.x = r1;
        block.block.position.z = r3;
        return block.block.__dirtyPosition = true;
      }));
      initInputStreams();
      chrmsm = (function() {
        var _i, _results;
        _results = [];
        for (num = _i = 1; _i <= 60; num = ++_i) {
          _results.push((Math.random() * 2.0) - 1.0);
        }
        return _results;
      })();
      nnConfig = new NNConfig([4, 10, 2], chrmsm);
      this.nn = new NN(nnConfig);
      this.updateBus = new Bacon.Bus();
      this.updateBus.onValue(function(ms) {
        return update(ms);
      });
      this.updateBus.onValue(function(ms) {
        return this.myBot.update();
      });
      this.generationResetTimer = this.updateBus.scan(0.0, (function(a, b) {
        return a + b;
      }));
      this.botPerceptionStream = this.updateBus.map(function(ms) {
        var v1, v2;
        v1 = getBotForwardVector(this.myBot);
        v2 = getClosestBlockVector(this.myBot);
        return [v1, v2];
      });
      this.botPerceptionStreamForNn = this.updateBus.map(function(ms) {
        var v1, v2;
        v1 = getBotForwardVector(this.myBot);
        v2 = getClosestBlockVector(this.myBot);
        return [v1.x, v1.z, v2.x, v2.z];
      });
      this.nnStream = this.botPerceptionStreamForNn.map(function(input) {
        return this.nn.evaluate(input);
      });
      this.nnStream.onValue(function(_arg) {
        var l, r;
        l = _arg[0], r = _arg[1];
        if (this.myBot != null) {
          return this.myBot.setInput(l, r);
        }
      });
      this.nnStream.onValue(this.myBot.update());
      this.botPerceptionStream.onValue((function(_arg) {
        var closestVec, forwardVec;
        forwardVec = _arg[0], closestVec = _arg[1];
        return renderBotPerceptions(forwardVec, closestVec);
      }));
      return updateUpdateBus();
    };
    updateCamera = function() {
      this.distance = 15;
      this.camera.position.y = this.distance * (Math.sin(this.altitude));
      return this.camera.position.z = this.distance * (Math.cos(this.altitude));
    };
    updatePicking = function() {
      this.intersects = [];
      if (this.mouse.x != null) {
        this.vector = new THREE.Vector3(this.mouse.x, this.mouse.y, -1);
        this.projector.unprojectVector(this.vector, this.camera);
        this.raycaster = new THREE.Raycaster(this.camera.position, this.vector.sub(this.camera.position).normalize());
        this.intersects = this.raycaster.intersectObjects(this.scene.children);
      }
      if (this.intersects.length > 0) {
        if (this.INTERSECTED !== this.intersects[0].object) {
          if ((this.INTERSECTED != null)) {
            this.INTERSECTED.material.emissive.setHex(this.INTERSECTED.currentHex);
          }
          this.INTERSECTED = this.intersects[0].object;
          this.INTERSECTED.currentHex = this.INTERSECTED.material.emissive.getHex();
          return this.INTERSECTED.material.emissive.setHex(0xff0000);
        }
      } else {
        if (this.INTERSECTED) {
          this.INTERSECTED.material.emissive.setHex(this.INTERSECTED.currentHex);
        }
        return this.INTERSECTED = null;
      }
    };
    this.oldTime = new Date;
    updateUpdateBus = function() {
      var ms;
      this.currentTime = new Date;
      ms = this.currentTime - this.oldTime;
      this.oldTime = this.currentTime;
      this.updateBus.push(ms);
      return window.requestAnimationFrame(updateUpdateBus);
    };
    evalFitness = function(simulatee) {
      return simulatee[0] * simulatee[0] + simulatee[1] * simulatee[1];
    };
    extractSimulatees = function() {
      var chromosome, _i, _len, _ref, _results;
      this.simulatees = [];
      _ref = this.ga.currentPopulation;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        chromosome = _ref[_i];
        _results.push(this.simulatees.push(chromosome));
      }
      return _results;
    };
    getBestFitness = function(fitnesses) {
      var fitness, min;
      min = fitnesses[0];
      if ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = fitnesses.length; _i < _len; _i++) {
          fitness = fitnesses[_i];
          _results.push(fitness < min);
        }
        return _results;
      })()) {
        min = fitness;
      }
      return min;
    };
    getAverageFitness = function(fitnesses) {
      var f, total, _i, _len;
      total = 0;
      for (_i = 0, _len = fitnesses.length; _i < _len; _i++) {
        f = fitnesses[_i];
        total += f;
      }
      return total / fitnesses.length;
    };
    updateGA = function(ms) {
      var averageFitness, bestFitness, fitnesses, simulatee, _i, _len, _ref;
      if (!(this.totalTime != null)) {
        this.totalTime = 0.0;
      }
      this.totalTime += ms;
      if (this.totalTime > (10.0 * 1000)) {
        fitnesses = [];
        _ref = this.simulatees;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          simulatee = _ref[_i];
          fitnesses.push(evalFitness(simulatee));
        }
        this.ga.update(fitnesses);
        bestFitness = getBestFitness(fitnesses);
        averageFitness = getAverageFitness(fitnesses);
        extractSimulatees();
        return this.totalTime = 0.0;
      }
    };
    getBotForwardVector = function(bot) {
      var v1, v2, v3;
      v1 = bot.body.localToWorld(new THREE.Vector3(0, 0, 1.0));
      v2 = bot.body.position;
      v3 = new THREE.Vector3().subVectors(v1, v2);
      return v3;
    };
    getClosestBlockVector = function(bot) {
      var block, closestBlock, minDist, t, v, v1, _i, _len, _ref;
      closestBlock = this.blocks[0];
      v = new THREE.Vector3().subVectors(bot.body.position, this.blocks[0].block.position);
      minDist = v.lengthSq();
      _ref = this.blocks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        block = _ref[_i];
        v = new THREE.Vector3().subVectors(bot.body.position, block.block.position);
        t = v.lengthSq();
        if (t < minDist) {
          minDist = t;
          closestBlock = block;
        }
      }
      v1 = (new THREE.Vector3().subVectors(closestBlock.block.position, bot.body.position)).normalize();
      return v1;
    };
    renderBotPerceptions = function(forwardVec, closestVec) {
      var geometry;
      if (!(this.line != null)) {
        geometry = new THREE.Geometry();
        geometry.vertices.push(this.myBot.body.position);
        geometry.colors.push(new THREE.Color(0xff0000), new THREE.Color(0xff0000));
        geometry.vertices.push(new THREE.Vector3().addVectors(this.myBot.body.position, forwardVec));
        geometry.colors.push(new THREE.Color(0xff0000), new THREE.Color(0xff0000));
        this.line = new THREE.Line(geometry);
        this.scene.add(this.line);
      } else {
        this.line.geometry.vertices[0] = this.myBot.body.position;
        this.line.geometry.vertices[1] = new THREE.Vector3().addVectors(this.myBot.body.position, forwardVec);
        this.line.geometry.verticesNeedUpdate = true;
      }
      if (!(this.lineToClosestBlock != null)) {
        geometry = new THREE.Geometry();
        geometry.vertices.push(this.myBot.body.position);
        geometry.colors.push(new THREE.Color(0xff0000), new THREE.Color(0xff0000));
        geometry.vertices.push(new THREE.Vector3().addVectors(this.myBot.body.position, closestVec));
        geometry.colors.push(new THREE.Color(0xff0000), new THREE.Color(0xff0000));
        this.lineToClosestBlock = new THREE.Line(geometry);
        return this.scene.add(this.lineToClosestBlock);
      } else {
        this.lineToClosestBlock.geometry.vertices[0] = this.myBot.body.position;
        this.lineToClosestBlock.geometry.vertices[1] = new THREE.Vector3().addVectors(this.myBot.body.position, closestVec);
        return this.lineToClosestBlock.geometry.verticesNeedUpdate = true;
      }
    };
    return update = function(ms) {
      this.scene.simulate();
      return this.renderer.render(this.scene, this.camera);
    };
  })();

}).call(this);
